name: project
description: A new Flutter project

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_size_text:
  align_positioned:
  eva_icons_flutter:
  get:
  flutter_screenutil:
  awesome_dialog:
  sentry_flutter:
  carousel_slider:
  cupertino_icons:
  flutter_svg: ^2.0.9
  url_launcher:
  lottie:
  internet_connection_checker:
  provider:
  google_map_location_picker_flutter:
  firebase_core:
  geolocator:
  geocoding:
  geocode:
  google_maps_flutter:
  connectivity_plus:
  flutter_spinkit:
  flutter_slidable:
  shimmer:
  firebase_auth:
  cloud_firestore:
  google_maps_place_picker_mb:
  shared_preferences:
  intl_phone_number_input: ^0.7.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons :

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/json/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
